#!/usr/bin/env python3

from optparse import OptionParser
from workload_analyzer import WorkloadAnalyzer

def main():
    parser = OptionParser()
    parser.add_option("-v", "--verbose", dest="verbose",
                      help="prints the detailed test data", action='store_true')
    parser.add_option("-p", "--plot", dest="plot",
                      help="plots the test results", action='store_true')
    parser.add_option("-s", "--save_plot", dest="save_plot",
                      help="save test result plots", action='store_true')
    parser.add_option("-a", "--archive", dest="archive",
                      help="archive the test results in an pickle file", action='store_true')
    parser.add_option("-c", "--capacity_factor", dest="capacity_factor",
                      help="returns the capacity factor", action='store_true')
    parser.add_option('-o', '--override_testname', dest='override_testname',
                      help='override the JSON test name', metavar='FILE')
    parser.add_option("-r", "--read_results", dest="read_results",
                      help="gather also the results of function invocations", action='store_true')
    (options, _) = parser.parse_args()

    WorkloadAnalyzer.main(options)


if __name__ == "__main__":
    main()
