#!/usr/bin/env python3

from optparse import OptionParser

from synthetic_workload_invoker.WorkloadInvoker import WorkloadInvoker

def main():
    parser = OptionParser()
    parser.add_option("-c", "--config_json", dest="config_json",
                      help="The input json config file describing the synthetic workload.", metavar="FILE")
    (options, _) = parser.parse_args()

    invoker = WorkloadInvoker()
    metadata = invoker.main(options)
    print("Finished benchmark with runid:", metadata["runid"])
    print("Failures/Successes/Expected: %s/%s/%s" %
          (metadata["failures"], metadata["successes"], metadata["expected"]))

if __name__ == "__main__":
    main()
